services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=uwu
      - POSTGRES_USER=uwu
      - POSTGRES_DB=db
